version: "3"

services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "3333:3333"
    links:
      - mongo
    volumes:
      - ".:/usr/server"
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
